<a href="https://colab.research.google.com/github/CodeAvecAsnit/codecloud/blob/main/AIandML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Single Dimensional Arrays

In [ ]:
import numpy as np

#create an array where all the elements are zero

np.zeros(5);


-Array with all the elements as one

In [ ]:
np.ones(6)
#here all the elements are gonna be one

array([1., 1., 1., 1., 1., 1.])

Crete an array where elemenets are given as n


In [ ]:
np.full(10 , 3)
#here the 10 represents the size of the array and 3 represents the element to be filled in the array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

lets create an array


In [ ]:
np.array([1 , 2, 3, 4, 5]);
#this creates a array with the elments inside the given elements

-create an array with range from n to x


In [ ]:
#Here the array starts from 3 to 14
np.arange(3,15)


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#create a array with a given linespace
arr = np.linspace(0 , 110 , 12)
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]


#Multidimensional Arrays

Create a array with all the elements as zero


In [ ]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Create an square matrix with all the elements as one


In [ ]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

now lets create a sequnece matrix with all the elements in sequnce from one to 9


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])



now replace with 20 for 2


In [ ]:
arr[0,1]=20;

now lets change the last row with 19


In [ ]:
arr[:,2]=2;
print(arr)

[[ 1 20  2]
 [ 4  5  2]
 [19 19  2]]


In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly Generated Arrays



-Np is able to create an array with random numbers.
-To ensure the reproductibility you can set a seed using np.random.seeed() . It will genrate the exacat same numbers for same execution.
-If you remove or change the seed values , the sequece of the numbers will be changed.

In [ ]:
print(np.random.rand(8))

[0.52267467 0.4783918  0.55535647 0.54338602 0.76089558 0.71237457
 0.6196821  0.42609177]


In [ ]:
print(np.random.seed(8))
print(np.random.rand(8))

None
[0.8734294  0.96854066 0.86919454 0.53085569 0.23272833 0.0113988
 0.43046882 0.40235136]


In [ ]:
np.random.randn(5,2)

array([[-2.29649157,  2.4098343 ],
       [ 1.72783617,  2.20455628],
       [ 0.79482764,  0.9764211 ],
       [-1.18342715,  1.91636361],
       [-1.1233268 , -0.66403547]])

#Element wise Operation on entire arrays element by element

In [ ]:
import numpy as np
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

comparision operators


In [ ]:
a>=2

array([False, False,  True,  True,  True])

In [ ]:
a>b

array([False, False, False, False, False])

In [ ]:
#summarizing of the data
#numpy provides the functions for summarizing array data
a.std()

1.4142135623730951

In [ ]:
a.sum()

10

In [ ]:
a.max()

4

In [ ]:
a.min()

0